# ──────────────────────────────────────────────────────────────────────────────
# MedPix medical cases — interleave, WebDataset, multi-image
# ──────────────────────────────────────────────────────────────────────────────
defaults:
  - _base_wds

output_name: medpix
output_dir: /capstor/store/cscs/swissai/infra01/vision-datasets/tokenized
manifest_path: /capstor/store/cscs/swissai/infra01/vision-datasets/medical/apertus_image_text_v1/medpix/manifest.parquet
text_column: txt

multi_image: true
image_field_pattern: img

parser: medpix


gpu_kmeans: false
seqlen_threshold: 8_192
