# ──────────────────────────────────────────────────────────────────────────────
# FaceCaption-15M — image2text, WDS tar
# ──────────────────────────────────────────────────────────────────────────────
defaults:
  - _base_wds

output_name: facecaption_15m
output_dir: /capstor/store/cscs/swissai/infra01/vision-datasets/tokenized
manifest_path: /capstor/scratch/cscs/xyixuan/manifests/facecaption_15m_cropped/manifest.parquet
text_column: caption

plan_path: /capstor/scratch/cscs/xyixuan/batch_plans/facecaption_15m_cropped.pt
checkpoint_interval_batches: 5_000

max_batch_tokens: 32_768
