# ──────────────────────────────────────────────────────────────────────────────
# BigDocs CORD-v2 — image-only, WebDataset
# ──────────────────────────────────────────────────────────────────────────────
defaults:
  - _base_wds

output_name: bigdocs_cordv2_wds
