# ──────────────────────────────────────────────────────────────────────────────
# LAION Aesthetics 12M — image-only, WebDataset
# ──────────────────────────────────────────────────────────────────────────────
defaults:
  - _base_wds

output_name: laion_aesthetics_12m
