# ──────────────────────────────────────────────────────────────────────────────
# SWISSIMAGE — image-only, WebDataset
# ──────────────────────────────────────────────────────────────────────────────
defaults:
  - _base_wds

output_name: swissimage
