# HuggingFace Arrow/Parquet storage.

dataset_type: hf

input_pattern: ???
image_column: image
image_list_column: null
multi_image: null
max_cached_chunks: 128

window_size: 2000
prefetch:
  queue_size: 32
